filter_tags: sbx

openshift_cluster_content:
- object: deployments
  content:
  - name: "deploy sbx environment"
    template: "{{ inventory_dir }}/../../.openshift/templates/deploy.yml"
    params: "{{ inventory_dir }}/../../.openshift/params/deploy-sbx"
    tags:
      - sbx
- object: jenkins-delta
  content:
  - name: "deploy delta jenkins image"
    template: openshift//delta-jenkins-v3-11
    params: "{{ inventory_dir }}/../../.openshift/params/delta-jenkins"
    namespace: sbx-p42660
    tags:
      - sbx
      - pipeline
- object: builds
  content:
  - name: "deploy build to sandbox"
    template: "{{ inventory_dir }}/../../.openshift/templates/build.yml"
    params: "{{ inventory_dir }}/../../.openshift/params/build-sbx"
    tags:
      - sbx
- object: builds
  content:
  -  name: "deploy build pipeline to dev"
     template: "{{ inventory_dir }}/../../.openshift/templates/build.yml"
     params: "{{ inventory_dir }}/../../.openshift/params/build-dvl"
     tags:
       - pipeline
- object: route
  content:
  - name: "create route"
    template: "{{ inventory_dir }}/../../.openshift/templates/route.yml"
    params: "{{ inventory_dir }}/../../.openshift/params/route-sbx"
    tags:
      - sbx
      - pipeline
