apiVersion: v1
kind: Template
labels:
  template: git-secret
metadata:
  annotations:
    description: git secret for credentials
    tags: secret
    version: 1.0.0
  name: git-secret
  namespace: ${NAMESPACE}
objects:
- apiVersion: v1
  data:
  stringData:
    ssh-privatekey: |-
      -----Enter you private key here-----
  kind: Secret
  metadata:
    name: git-secret
    namespace: ${NAMESPACE}
  type: kubernetes.io/ssh-auth
parameters:
- description: The namespace to create secret
  name: NAMESPACE
  required: true
